### ISSUE TITLE
Rubberduck Add-In could not be loaded

### ISSUE THREAD

**Issue by gsf-greece** [rubberduck-vba/Rubberduck#1019]
Sorry If this has been reported in the past but I couldn't find any issue open or closed about this. I have just downloaded the latest release from GitHub, installed it to my Windows 10 system, then I tried to load the Add-in from within MS-Access 2016.

Unfortunately I get an error that the Add-in could not be loaded, but I can see a new menu called rubberduck, and I can use some of its functions (I have no idea if all of them are there or if they are working properly after getting that error). 
![rubberduck-error](https://cloud.githubusercontent.com/assets/6191600/12747332/18e82824-c9ac-11e5-88cf-37846df86c09.PNG)

Then if I try to close MS-Access, I get an error that my database might be corrupted and that it tries to recover my information, then ms-access creates a backup file of the database. Is there anything I can do to fix that at the moment?

**Comment by retailcoder** [comment]
Hi @gsf-greece, thanks for trying our Rubberduck!

Please confirm that you have installed the add-in following the steps in the [Installing](https://github.com/rubberduck-vba/Rubberduck/wiki/Installing) page; the installer requires administrative privileges to correctly register its COM components; if you're not logged in as the local admin user that was logged in during the installation, the add-in isn't registered correctly for your user, see [installing for non-admin users](https://github.com/rubberduck-vba/Rubberduck/wiki/Installing#installing-for-non-admin-users).

Hope it helps!

**Comment by gsf-greece** [comment]
Hi and thanks for looking into this. I just uninstalled and installed the add-in again by clicking Run as Administrator, but the same thing happens. I get the same error, and I can still see the rubberduck menu. But MS-Access keeps crashing when I close or open it while having rubberduck enabled. 

![rubberduck-menu](https://cloud.githubusercontent.com/assets/6191600/12756337/015e7976-c9dc-11e5-97e0-2ad93a503a32.PNG)

**Comment by Hosch250** [comment]
It looks like all the items are there.  This sounds like our old "friend" the memory leak again.  We use unmanaged resources, and it is very difficult to ensure they are all cleaned up.

**Comment by retailcoder** [comment]
hmm well having the Rubberduck menu there, sounds like there's progress - the add-in *does* load. The host app crashing on exit is a completely different issue though.

**Comment by gsf-greece** [comment]
Is there a way to provide you with logs? I looked into the rubberduck directory but I can't see anything.

**Comment by Hosch250** [comment]
Check C:\Users\{username}\AppData\Roaming\Rubberduck\logs

**Comment by retailcoder** [comment]
@Hosch250  that would only be for parser errors IIRC

**Comment by Hosch250** [comment]
OK, I thought so.  The description sounds exactly like that pesky memory leak which I had fixed at one point (it is really acting up again, I'll have to fix it before we release 2.0).

**Comment by gsf-greece** [comment]
An additional issue, without changing anything, the add-in has now disappeared from ms-access. I also tried to re-install but it is still missing. I also checked the regedit entries and they are all where they should be, according to the wiki. I also checked for logs in C:\Users{username}\AppData\Roaming\Rubberduck\logs but the Rubberduck directory is missing from there.

**Comment by Hosch250** [comment]
I'm not sure what is happening here.  Maybe Rubberduck 2.0, with vague release deadline of sometime in the next 6-8 years (just kidding, we *hope* to release it in a few months) will fix this.

**Comment by AndrewM-** [comment]
I am using ms-access 2016 on a new machine running win 10 and get the following dialog when trying to open the VBE Editor.

![2016-12-09rubberduck add-in could not be loaded](https://cloud.githubusercontent.com/assets/5060805/21030867/729b7a3a-bdec-11e6-92b8-de27a91d83d8.jpg)

I initially installed RD 2.0.9 as an ordinary user and then read that I need to install with administrative privileges, so I uninstalled and ran the installer as an administrator.  I got the same dialog.  When you mention installing with administrative privileges do you mean logging in as an administrator or logging in as a normal user then running the installer as an administrator?   On my ms-access 2010 machine, I just ran the installer without administrator privileges and RD works fine.

**Comment by retailcoder** [comment]
@AndrewM- TBH I have no idea why the Vbe.Forms interop assembly might be missing *sometimes* and work fine in other installs - but that specific problem is definitely fixed in the current 2.0.10 build, which is starting to look pretty damn stable, at least on my work laptop (it somehow still crashes on exit in other environments though) - we'll be releasing 2.0.10 soon, like, a week or two.
