### ISSUE TITLE
System.AccessViolationException thrown in User32.CallWindowProc

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1268]
Line 163 in RubberduckHooks causes a System.AccessViolationException, crashing the host application. The code:

```
                if (!processed)
                {
                    return User32.CallWindowProc(_oldWndProc, hWnd, uMsg, wParam, lParam);
                }
```

Tested with Excel/Word, both 64bit. Win10 64bit.

**Comment by Pitterling** [comment]
i have the same issue - both 64bit - Office 2016
but also with the latest commit, i'm not even able to load on 32bit Excel ... 

System.ArgumentException: An item with the same key has already been added ...

**Comment by autoboosh** [comment]
Problem is fixed with the latest PR. The second problem you mentioned seems to be a problem with the key hooks. There's already a separate issue for that here: #1273.

**Comment by Pitterling** [comment]
hmmm ... i'm still facing this issue

> System.AccessViolationException was unhandled
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=Rubberduck
  StackTrace:
       at Rubberduck.Common.WinAPI.User32.CallWindowProc(WndProc lpPrevWndFunc, IntPtr hWnd, Int32 Msg, Int32 wParam, Int32 lParam)
       at Rubberduck.Common.RubberduckHooks.WindowProc(IntPtr hWnd, Int32 uMsg, Int32 wParam, Int32 lParam) in C:\Code\Tools\Rubberduck\RetailCoder.VBE\Common\RubberduckHooks.cs:line 163
  InnerException: 

Shall I open a new issue?

**Comment by autoboosh** [comment]
It looks like you are still using the old rubberduck version. Did you update to the latest version in next? The CallWindowProc signature still shows the old, problematic parameter types.

**Comment by Pitterling** [comment]
I refreshed my repo and did a clean build

**Comment by autoboosh** [comment]
1. Does the Msg-Parameter in the CallWindowProc signature in the User32 class in Rubberduck.Common.WinAPI have type uint?
2. Did you start Rubberduck via Visual Studio?
3. Did you rename the rubberduck project (leading to the registered .dll not being updated)
4. There might be old rubberduck dlls lying around. Does your office folder have any rubberduck dlls? If so delete them.

Of course there could still be a problem but judging from your stack trace it seems that for some reason your host application (Excel, Word, ...) still uses the old version.

**Comment by Pitterling** [comment]
I used the Debug64 configuration .. it seems that the dll registration is always pointing to the debug directory .. here I still had an old DLL
![image](https://cloud.githubusercontent.com/assets/4181164/14225972/e5d1e2fa-f8d5-11e5-8c95-00013f62aafb.png)

**Comment by autoboosh** [comment]
That has happened a few times to me as well. Make sure to also delete the rubberduck config file in your %APPDATA%\Rubberduck folder since some changes were made recently to the config file.

**Comment by Pitterling** [comment]
i removed the config file. deleted all DLLs and built DEBUG64 ... 
![image](https://cloud.githubusercontent.com/assets/4181164/14226054/79e6f81c-f8d7-11e5-85ca-000187e080d6.png)

Excels says ...
![image](https://cloud.githubusercontent.com/assets/4181164/14226057/88ea0c3c-f8d7-11e5-8750-8b792d7be771.png)

**Comment by autoboosh** [comment]
If you follow the steps described in the contributing page then you have probably registered the rubberduck dlls in the Debug folder: https://github.com/rubberduck-vba/Rubberduck/wiki/Contributing. Now that you've deleted them you should also rebuilt them. Either copy paste the ones from your Debug64 folder or simply switch to Debug from Debug64 and rebuild.

**Comment by Pitterling** [comment]
thx a lot. I'm using 2 environments - 32 and 64bit office and I used the configuration DEBUG|DEBUG64 to adjust the path to the right excel.exe file.
I reregistered on my 64bit environment the correct rubberduck.dll from the debug64 directory and now it works as expected. thanks again.

**Comment by autoboosh** [comment]
No problem :)
