### ISSUE TITLE
can´t get Rubberduck 2.0.1a-pre working in Access

### ISSUE THREAD

**Issue by woxovvoxow** [rubberduck-vba/Rubberduck#1552]
Hi,

I'm very interested in your Project providing an up-to-date VBE!
Everything I've seen so far looks very promising.

My environment is the following:
- Windows 7 Enterprise Servicepack 1 (64 bit)
- MS Access 2010 (14.0.7162.5001) SP2 MSO (14.0.7166.5000)
- I have local-admin-rights on my machine  
- C:\Windows\Microsoft.NET\Framework\v4.0.30319
- C:\Windows\Microsoft.NET\Framework64\v4.0.30319

(obviously both 32bit and 64bit .NET Framework)

Rubberduck was installed with lokal Admin-Rights

when I open Access-VBE the following Error occurs: 

![image](https://cloud.githubusercontent.com/assets/10561922/15420870/5ab13058-1e6f-11e6-8597-286ac3b80af0.png)

The Details show following information:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> *************\* Exception Text **************
> System.Runtime.InteropServices.COMException (0x8002801D): Bibliothek nicht registriert. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED))
>    at Microsoft.Vbe.Interop.Reference.get_FullPath()
>    at Rubberduck.Parsing.VBA.RubberduckParser.<>c__DisplayClass9.<GetReferenceProjectId>b__8(VBProject project) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 211
>    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Rubberduck.Parsing.VBA.RubberduckParser.GetReferenceProjectId(Reference reference, IReadOnlyList`1 projects) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 207
>    at Rubberduck.Parsing.VBA.RubberduckParser.SyncComReferences(IReadOnlyList`1 projects) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 235
>    at Rubberduck.Parsing.VBA.RubberduckParser.AddBuiltInDeclarations(IReadOnlyList`1 projects) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 171
>    at Rubberduck.Parsing.VBA.RubberduckParser.ParseAll() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 140
>    at Rubberduck.Parsing.VBA.RubberduckParser.ReparseRequested(Object sender, ParseRequestEventArgs e) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 77
>    at Rubberduck.Parsing.VBA.RubberduckParserState.OnParseRequested(Object requestor, VBComponent component) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 534
>    at Rubberduck.App.<Startup>b__1() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\App.cs:line 139
>    at Rubberduck.UI.Command.MenuItems.UiDispatcher.<>c__DisplayClass1.<InvokeAsync>b__0(Object x) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\MenuItems\UiDispatcher.cs:line 28

I already tried your hin "Troubleshooting: Rubberduck Add-In could not be loaded"
and succeeded in registering Rubberduck.dll - but nothing changed.

after clicking un "Continue" i can start for example the Test-Explorer, but nothing is working properly.

Closing Access it crashes.

any Ideas?

**Comment by Hosch250** [comment]
Please check out the beta.  We fixed a bunch of bugs since the alpha release, and this may well be one of them.

**Comment by woxovvoxow** [comment]
Hi,

I tried the version 2.0.b, 2.0.1b and 2.0.2b now. The behaviour changed a bit in that way, that there's no Error-message any more, but It is still not working.
Starting for the first time the addin is loading, but for exaple the test-explorer does'nt recognize its tests:

![image](https://cloud.githubusercontent.com/assets/10561922/16184189/7c3f4454-36ba-11e6-845b-4e91de376733.png)

The menu Code-Inspection is not working as well - it is showing no results at all.
At least every 2.nd time Access is not closed properly - I have to kill the MSACCESS-process in Task-Manager.

for me it looks like I still have an issue with no proper installation / registration or so.

any help appriciated - I was dreaming to have a VBE like this (at least what I can see from your Site) and now it is not installabe properly on my machine... :-(

**Comment by woxovvoxow** [comment]
...closed accidentially..

**Comment by Hosch250** [comment]
Looks like it is not parsing.  The Code Inspections, Test Explorer, Code Explorer, and Todo Explorer all require there be a successful parse and resolve to work.  If you have a very large project, it could take a while--what does the status bar say?  The host app not closing properly is a known issue being addressed.

**Comment by woxovvoxow** [comment]
You are right, it is obviously not parsing.
The project is just a Test for the Addin - only 2 Modules - so there should be no performance issue.

![image](https://cloud.githubusercontent.com/assets/10561922/16218025/a82b3b6c-3779-11e6-9f23-97575cb73eb6.png)

The status bar displays "Referenzen werden geladen" (resolving).

so it seems to be the same issue as #1843.

**Comment by Vogel612** [comment]
Actually that's not quite correct. The status bar says "loading references..." which is different from resolving. #1843 is not related

**Comment by woxovvoxow** [comment]
Meanwhile I installed 2.0.3b.

I found out that code-Inspection seems to be ok (loading references - parsing - ready) as long as I dont add a reference on Rubbeduck.tlb (for Unit-Testing).
Once I add the reference, close Access and reopen it, Rubberduck gets stuck in "loadin references".
Sometimes a click on the refresch button next to the status starts a proper parsing (stops with ready) sometimes not...

**Comment by Hosch250** [comment]
OK, thanks for the updates.

**Comment by woxovvoxow** [comment]
unfortunately no change with 2.0_RC1 here... :-(

Trying to add a test-Procedure Rubberduck crashes with the hint to send the logfile.
Where can I find the log? 
The only file i found "Rubberduck.App.log" has a change-Date in Mai...

**Comment by retailcoder** [comment]
Is it just Access, or Excel doesn't work either? You can get to the logs via the settings dialog; from there you can also set minimum log level to 'Trace' to log *everything*. Hopefully *something* gets logged.. what version of Access are you using?

**Comment by retailcoder** [comment]
Nevermind, saw Access 2010 in the original post

**Comment by woxovvoxow** [comment]
OK, thanks - I switched Logging to "Debugging".
Attached you can find what happens, when I try to add a Test-Method:

(renamed rubberduck.log to rubberduck.txt for Upload)

[rubberduck.txt](https://github.com/rubberduck-vba/Rubberduck/files/346281/rubberduck.txt)

**Comment by Hosch250** [comment]
Looks like a failing Single call.  I wonder what's up there.

**Comment by Hosch250** [comment]
I just changed this to do nothing in this case.  I'm not even sure why this even happens (the commands should be disabled...)
