### ISSUE TITLE
Code explorer is empty

### ISSUE THREAD

**Issue by INOPIAE** [rubberduck-vba/Rubberduck#1558]
Working on 118f532  in Excel 2010
The code explorer shows an empty window.
I get a message Parser Error
When opening the result window it is empty.
Opening the result window several times I get multiple tabs in the window that are empty
![image](https://cloud.githubusercontent.com/assets/2772829/15447290/183cfb42-1f3e-11e6-97fe-3f974dde8425.png)

**Comment by Hosch250** [comment]
I don't know what's up with this, but if you get a parser error on the very first parse, the code explorer will be empty, and there is nothing we can do about it.

**Comment by retailcoder** [comment]
@Hosch250 shouldn't it yield error nodes in the tree?

**Comment by Hosch250** [comment]
Ummm, I guess it should--at the component level.  I'll take a look on Monday.

**Comment by autoboosh** [comment]
Do you have some example code that's causing the parser error?

**Comment by retailcoder** [comment]
@Hosch250 we'll have to do something about refreshing the *parser errors* tab instead of making a new one everytime the parser error button is clicked.

**Comment by Hosch250** [comment]
Please check the CE problem on the latest commit.

**Comment by INOPIAE** [comment]
I still get an empty CE using be38cf2

**Comment by Hosch250** [comment]
Could you share the workbook?  It is correctly loading modules with errors for me.

**Comment by Hosch250** [comment]
I can't reproduce this issue.

**Comment by transistor1** [comment]
FWIW, I get the same issue in all of my msaccess projects at work using latest rubberduck build.  They have several references to other complex acesss projects with a bunch of modules.  I cant share the databases because they belong to my company. However it's the same issue - blank code explorer with no decscription of errors.  The rubberduck toolbar does say parsing error, though.

**Comment by Hosch250** [comment]
Latest release, or latest build?

**Comment by transistor1** [comment]
It was the latest build.  I just did a git pull this morning (8:25 AM EST) and rebuilt it (4b185ee), and now I'm just getting a crash while it's doing its initial parse: "The expression you entered refers to an object that is closed or doesn't exist".

![image](https://cloud.githubusercontent.com/assets/5625360/15674533/43090b0c-270b-11e6-9859-7c28fd351dfa.png)

**Comment by Hosch250** [comment]
That is another known issue that @ThunderFrame just resolved.  He is testing it now.

**Comment by transistor1** [comment]
Thanks. Do you think that might fix the empty parse errors window too?  Do you know the issue # of his fix?  I'd like to pull it as soon as it's merged.

**Comment by Hosch250** [comment]
I'll let you know when it is merged--he is still testing it in his fork.  I have no idea what is causing the empty parse errors window--I've only duplicated that once, but a refresh fixed it.

**Comment by transistor1** [comment]
Thanks... If I have time I'll try to track it down.  Unfortunately, I can't debug on my work machine b/c it has Visual Studio 2010, and it won't debug Framework 4.5.  I had to build Rubberduck with MSBuild.  If I have time I'll try to narrow the problem down.

**Comment by Hosch250** [comment]
Thanks.

**Comment by Hosch250** [comment]
I doubt anything changed, but I just fixed a pretty major bug with the cache, if you want to check again.

**Comment by transistor1** [comment]
Some progress... using build 83b08c4.  I'm still getting a NullReferenceException on initial parse (but now at RubberduckParserState line 162 -- that's different than the previous one).

But, now the Parser Errors window is no longer empty.  It reads:
```
Member: Miscellaneous Functions
Type: Module
Location: L715C9
Context: no viable alternative at input ("Menu Bar"). _\r\n      Controls
```

Looks like an Antlr grammar issue.

The lines in question are:

```
Function Compact_Open_Database()
    CommandBars("Menu Bar"). _
        Controls("Tools"). _
        Controls("Database utilities"). _
        Controls("Compact and repair database..."). _
        accDoDefaultAction
End Function

```

P.S: Pls. pardon any typos: I had to type the code in rather than copy-paste.

**Comment by transistor1** [comment]
Scratch that.  I hadn't double-checked that VBA before I posted.. it's not even valid.  Some leftover cruft from an old project.  So, I commented it out and the project parses fine.

Now the code explorer is populating.  Should I open another issue for the NullReferenceException?  It only appears to be happening when the project in question is being referenced by an external database.

**Comment by transistor1** [comment]
Probing a little further... the snippet I posted above does illustrate a problem.  This valid snippet doesn't parse (no viable alternative):

```
Sub Valid_Snippet_With_Parse_Error()

    Set app = CommandBars("Menu Bar"). _
        Application

    Debug.Print app.Name

End Sub
```

**Comment by transistor1** [comment]
Issue #1650 created for previous comment

**Comment by retailcoder** [comment]
Closing as fixed, since the code explorer is populating. Thanks!
