### ISSUE TITLE
Initial parse on empty Access.accdb hangs

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2717]
RD 2.0.11 Access2010 Win7

I opened a new, blank Access project, saved it with the one default table with the one default column. Opened the VBE, clicked parse and... went to the bathroom, took the elevator down to the lobby, got a drink, rode the elevator back up, and it's still Pending.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/790570/RubberduckLog.txt)

Clicking the `Pending` button to refresh only generated additional sets of the 2 lines in the log.

**Comment by retailcoder** [comment]
I *think* that cannot be replicated in the current build.

**Comment by ThunderFrame** [comment]
Does taking the stairs to the lobby help? ;-P

**Comment by daFreeMan** [comment]
@ThunderFrame it helps with the plan for losing weight, but not as much as taking the stairs to the 9th floor.

**Comment by retailcoder** [comment]
Fixed?

**Comment by bclothier** [comment]
Just tried to reproduce this. There seems to be 2 separate issues:

1) Access does not auto-parse at startup like Excel. That is still an issue, though one that is likely hard to fix since AIUI, we rely on events raised by VBE IDE, and it might be just not firing in time with different host.

2) An empty VBA project has nothing to parse, so it'll remain at `Pending` even after clicking. I think that is by design. This cannot be easily observed in Excel or other hosts where there are always at least one document module.

Note that if a database file with a VBA project (just an empty module will suffice) is closed & reopened via Access (using `File` -> `Close Database`, followed by `File` -> `Recent` -> `<the file that we just closed>`), Rubberduck is able to correctly automatically parse the reloaded project and will enter `Ready` state without manual clicking. So we know we can observe the project loading and thus auto-parse but we just cannot do it when we are loading VBE for first time.

**Comment by MDoerner** [comment]
I think the first point is something we really cannot do anything about. Even in Excel, once your project gets a bit bigger, parsing on startup no longer works. We are at the mercy of the VBE there.

I will handle the second point.
