### ISSUE TITLE
'Find All References' returns a factor of actual references

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#3038]
As show in the image 10 are being reported when only 5 exist.
![references count greater than actual references](https://cloud.githubusercontent.com/assets/26076874/26474203/7ff80a44-4164-11e7-92fe-982a1c2e2c03.PNG)

**Comment by retailcoder** [comment]
Is this off the current build / "next"? I've noticed this as well in the .13 build.

Does refreshing/reparsing affect/fix/worsen the issue?

**Comment by IvenBach** [comment]
Screenshot is from current build.

**Comment by Vogel612** [comment]
Considered critical, because mismatching reference counts (and reference pointers) will break refactorings in funky ways... Should be fixed before next release.

**Comment by retailcoder** [comment]
@IvenBach your fork seems to be a number of commits behind. A diff against [next] shows a lot of @MDoerner 's work missing, and against [IvenBach-next] there are merge conflicts to resolve; not sure which branch you're working off, but you'll want to `git pull upstream next` regularly to keep up with changes from other contributors (assuming you have `rubberduck-vba/Rubberduck` upstream).

**Comment by IvenBach** [comment]
I'll look at it tonight. Every time I work on something I make sure to do a pull first. May be that I haven't pushed it to my fork. Still not fully used to Git it seems.

**Comment by retailcoder** [comment]
Confirming repro with 2.0.13 release build:

![55/11 references](https://cloud.githubusercontent.com/assets/5751684/26696185/81c138f6-46db-11e7-81e0-ace81355a593.png)

The factor is 5x here - after another reparse the factor becomes 6x. Definitely some cached references not being cleared when they should. Will confirm if I can repro with current build later.

**Comment by retailcoder** [comment]
@Vogel612 not sure it's [critical] though - seems the parser state does have the correct number of references (*find all refs* navigates directly to target when reported count is 6 / actual is 1). Looks more like a UI issue.

**Comment by MDoerner** [comment]
The number of references should have been right in the parser in 2.0.13 for user defined declarations. For built-in ones it was definitely broken. See issue #3002.

**Comment by Vogel612** [comment]
soo ... #fixed?

**Comment by Vogel612** [comment]
What's the status on this? @rubberduck-vba/dev
