### ISSUE TITLE
No RD menu item in context menus

### ISSUE THREAD

**Issue by ghost** [rubberduck-vba/Rubberduck#3095]
Rubberduck menu is not injected into any context (right-click) menus.  See screenshot.

I am successfully running a recent build of the Next branch,
Excel 2013 64-bit
Windows 7 64-bit

![no_rubberduck_menu](https://user-images.githubusercontent.com/28154402/27738437-f1087502-5d70-11e7-8379-3e46c7a76434.png)

**Comment by shadowofsilicon** [comment]
Should mention, works on Excel 2016 32-bit on Windows 10 64-bit.

**Comment by retailcoder** [comment]
Ugh. I think I removed the menu-creation log entries... or does .13 still log them? In any case I'm pretty sure the debug output would show menu creation details... if you run the debug build from Visual Studio, and bring up the "Output" (debug) toolwindow, there could be a hint or two there.

**Comment by shadowofsilicon** [comment]
Results from the Output tool window in VS2017:

```
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Rubberduck.dll'. Symbols loaded.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\NLog.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.Vbe.Interop\15.0.0.0__71e9bce111e9429c\Microsoft.Vbe.Interop.dll'. Module was built without symbols.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Microsoft.VB6.Interop.VBIDE.dll'. Module was built without symbols.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Rubberduck.VBEditor.dll'. Symbols loaded.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Rubberduck.SettingsProvider.dll'. Symbols loaded.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'Microsoft.GeneratedCode'. 
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Ninject.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Ninject.Extensions.Factory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Ninject.Extensions.Interception.DynamicProxy.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Ninject.Extensions.Interception.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Castle.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Rubberduck.Parsing.dll'. Symbols loaded.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Rubberduck.SourceControl.dll'. Symbols loaded.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Rubberduck.SmartIndenter.dll'. Symbols loaded.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Ninject.Extensions.NamedScope.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Rubberduck.Inspections.dll'. Symbols loaded.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Antlr4.Runtime.net45.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\ICSharpCode.AvalonEdit.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\ELECTA~1\AppData\Local\Temp\VisualStudio.XamlDiagnostics.4848\Microsoft.VisualStudio.DesignTools.WpfTap.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Microsoft.Vbe.Interop.Forms.dll'. Module was built without symbols.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\assembly\GAC_MSIL\office\15.0.0.0__71e9bce111e9429c\office.dll'. Module was built without symbols.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Ninject.Extensions.Conventions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'DynamicProxyGenAssembly2'. 
The thread 0x1194 has exited with code 0 (0x0).
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'DynamicProxyGenAssembly2'. 
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsFormsIntegration\v4.0_4.0.0.0__31bf3856ad364e35\WindowsFormsIntegration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.IdentityModel\v4.0_4.0.0.0__b77a5c561934e089\System.IdentityModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\Infralution.Localization.Wpf.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll'. Cannot find or open the PDB file.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'DynamicProxyGenAssembly2'. 
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'DynamicProxyGenAssembly2'. 
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.DurableInstancing\v4.0_4.0.0.0__31bf3856ad364e35\System.Runtime.DurableInstancing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'Microsoft.GeneratedCode'. 
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'Microsoft.GeneratedCode'. 
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'Microsoft.GeneratedCode'. 
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'Microsoft.GeneratedCode'. 
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'Microsoft.GeneratedCode'. 
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'Microsoft.GeneratedCode'. 
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2017-06-30 09:11:46.7338;TRACE;Rubberduck.UI.DockableToolwindowPresenter;Initializing Dockable Panel (InspectionResultsDockablePresenter);
SubclassingWindow.AssignHandle called for hWnd 132116
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
TestEngine created.
2017-06-30 09:11:47.1706;TRACE;Rubberduck.UI.DockableToolwindowPresenter;Initializing Dockable Panel (TestExplorerDockablePresenter);
SubclassingWindow.AssignHandle called for hWnd 132100
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'Microsoft.GeneratedCode'. 
2017-06-30 09:11:47.5433;TRACE;Rubberduck.UI.SourceControl.SourceControlViewViewModel;Setting active tab to Changes;
2017-06-30 09:11:47.5753;TRACE;Rubberduck.UI.DockableToolwindowPresenter;Initializing Dockable Panel (SourceControlDockablePresenter);
SubclassingWindow.AssignHandle called for hWnd 131906
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2017-06-30 09:11:47.8863;TRACE;Rubberduck.UI.DockableToolwindowPresenter;Initializing Dockable Panel (ToDoExplorerDockablePresenter);
SubclassingWindow.AssignHandle called for hWnd 132018
2017-06-30 09:11:48.3193;TRACE;Rubberduck.UI.DockableToolwindowPresenter;Initializing Dockable Panel (CodeExplorerDockablePresenter);
SubclassingWindow.AssignHandle called for hWnd 132028
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_64\CustomMarshalers\v4.0_4.0.0.0__b03f5f7f11d50a3a\CustomMarshalers.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
SubclassingWindow.AssignHandle called for hWnd 459934
2017-06-30 09:11:48.5832;INFO;Rubberduck.App;Rubberduck version 2.0.14.14694 loading:
	Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1 x64
	Host Product: Microsoft Office 2013 x64
	Host Version: 15.0.4937.1000
	Host Executable: EXCEL.EXE;
2017-06-30 09:11:48.6082;TRACE;Rubberduck.App;Checking for legacy Smart Indenter settings.;
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\assembly\GAC\stdole\7.0.3300.0__b03f5f7f11d50a3a\stdole.dll'. Module was built without symbols.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Dynamic\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Dynamic.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'System.Dynamic.DynamicAssembly'. 
Added handler for: Rubberduck '' (tag: Rubberduck.UI.Command.MenuItems.CommandBars.ReparseCommandMenuItem, hashcode:37982174)
Added handler for: Rubberduck 'Serialize' (tag: Rubberduck.UI.Command.MenuItems.CommandBars.SerializeDeclarationsCommandMenuItem, hashcode:6295248)
Added handler for: Rubberduck '' (tag: Rubberduck.UI.Command.MenuItems.CommandBars.ShowParserErrorsCommandMenuItem, hashcode:56657239)
Added handler for: Rubberduck '' (tag: Rubberduck.UI.Command.MenuItems.CommandBars.ReferenceCounterLabelMenuItem, hashcode:40153107)
Added handler for: Custom Popup 2699269 '&Test Explorer' (tag: Custom Popup 2699254::RubberduckMenu_UnitTests::TestExplorerCommandMenuItem, hashcode:25833645)
Added handler for: Custom Popup 2699269 '&Run All Tests' (tag: Custom Popup 2699254::RubberduckMenu_UnitTests::RunAllTestsCommandMenuItem, hashcode:31176214)
Added handler for: Custom Popup 2699269 'Test M&odule' (tag: Custom Popup 2699254::RubberduckMenu_UnitTests::AddTestModuleCommandMenuItem, hashcode:12150471)
Added handler for: Custom Popup 2699269 'Test &Method' (tag: Custom Popup 2699254::RubberduckMenu_UnitTests::AddTestMethodCommandMenuItem, hashcode:42245377)
Added handler for: Custom Popup 2699269 'Test Method (&Expected Error)' (tag: Custom Popup 2699254::RubberduckMenu_UnitTests::AddTestMethodExpectedErrorCommandMenuItem, hashcode:44664077)
Added handler for: Custom Popup 2699285 'Current &Procedure' (tag: Custom Popup 2699254::SmartIndenterMenu::IndentCurrentProcedureCommandMenuItem, hashcode:66432381)
Added handler for: Custom Popup 2699285 'Current &Module' (tag: Custom Popup 2699254::SmartIndenterMenu::IndentCurrentModuleCommandMenuItem, hashcode:61020521)
Added handler for: Custom Popup 2699285 'Current Project' (tag: Custom Popup 2699254::SmartIndenterMenu::IndentCurrentProjectCommandMenuItem, hashcode:12313777)
Added handler for: Custom Popup 2699285 '&Add '@NoIndent' (tag: Custom Popup 2699254::SmartIndenterMenu::NoIndentAnnotationCommandMenuItem, hashcode:43715136)
Added handler for: Custom Popup 2699300 '&Rename' (tag: Custom Popup 2699254::RubberduckMenu_Refactor::CodePaneRefactorRenameCommandMenuItem, hashcode:57891910)
Added handler for: Custom Popup 2699300 'Extract &Method' (tag: Custom Popup 2699254::RubberduckMenu_Refactor::RefactorExtractMethodCommandMenuItem, hashcode:51265148)
Added handler for: Custom Popup 2699300 'E&xtract Interface' (tag: Custom Popup 2699254::RubberduckMenu_Refactor::RefactorExtractInterfaceCommandMenuItem, hashcode:58733156)
Added handler for: Custom Popup 2699300 '&Implement Interface' (tag: Custom Popup 2699254::RubberduckMenu_Refactor::RefactorImplementInterfaceCommandMenuItem, hashcode:58836357)
Added handler for: Custom Popup 2699300 'Remo&ve Parameters' (tag: Custom Popup 2699254::RubberduckMenu_Refactor::RefactorRemoveParametersCommandMenuItem, hashcode:59765170)
Added handler for: Custom Popup 2699300 'Re&order Parameters' (tag: Custom Popup 2699254::RubberduckMenu_Refactor::RefactorReorderParametersCommandMenuItem, hashcode:1015618)
Added handler for: Custom Popup 2699300 'Move Closer To &Usage' (tag: Custom Popup 2699254::RubberduckMenu_Refactor::RefactorMoveCloserToUsageCommandMenuItem, hashcode:9140568)
Added handler for: Custom Popup 2699300 '&Encapsulate Field' (tag: Custom Popup 2699254::RubberduckMenu_Refactor::RefactorEncapsulateFieldCommandMenuItem, hashcode:15156252)
Added handler for: Custom Popup 2699300 'Introduce &Parameter' (tag: Custom Popup 2699254::RubberduckMenu_Refactor::RefactorIntroduceParameterCommandMenuItem, hashcode:2188543)
Added handler for: Custom Popup 2699300 'Introduce &Field' (tag: Custom Popup 2699254::RubberduckMenu_Refactor::RefactorIntroduceFieldCommandMenuItem, hashcode:19696890)
Added handler for: Custom Popup 2699363 '&Code Explorer' (tag: Custom Popup 2699254::RubberduckMenu_Navigate::CodeExplorerCommandMenuItem, hashcode:43054286)
Added handler for: Custom Popup 2699363 'Find &symbol...' (tag: Custom Popup 2699254::RubberduckMenu_Navigate::FindSymbolCommandMenuItem, hashcode:51944261)
Added handler for: Custom Popup 2699363 '&Find all references...' (tag: Custom Popup 2699254::RubberduckMenu_Navigate::FindAllReferencesCommandMenuItem, hashcode:64845166)
Added handler for: Custom Popup 2699363 'Go to &implementation...' (tag: Custom Popup 2699254::RubberduckMenu_Navigate::FindAllImplementationsCommandMenuItem, hashcode:46735588)
Added handler for: Custom Popup 2699378 '&Source Control' (tag: Custom Popup 2699254::ToolsMenu::SourceControlCommandMenuItem, hashcode:17967111)
Added handler for: Custom Popup 2699378 'To&Do Items' (tag: Custom Popup 2699254::ToolsMenu::ToDoExplorerCommandMenuItem, hashcode:27486272)
Added handler for: Custom Popup 2699378 'Regex &Assistant' (tag: Custom Popup 2699254::ToolsMenu::RegexAssistantCommandMenuItem, hashcode:46049856)
Added handler for: Custom Popup 2699254 'Code &Inspections' (tag: Menu Bar::RubberduckMenu::InspectionResultsCommandMenuItem, hashcode:11795520)
Added handler for: Custom Popup 2699254 'S&ettings' (tag: Menu Bar::RubberduckMenu::SettingsCommandMenuItem, hashcode:39050817)
Added handler for: Custom Popup 2699254 '&About...' (tag: Menu Bar::RubberduckMenu::AboutCommandMenuItem, hashcode:15913036)
Added handler for: Custom Popup 2699410 '&Rename' (tag: Custom Popup 2699394::RubberduckMenu_Refactor::CodePaneRefactorRenameCommandMenuItem, hashcode:8999603)
Added handler for: Custom Popup 2699410 'Extract &Method' (tag: Custom Popup 2699394::RubberduckMenu_Refactor::RefactorExtractMethodCommandMenuItem, hashcode:13887565)
Added handler for: Custom Popup 2699410 'E&xtract Interface' (tag: Custom Popup 2699394::RubberduckMenu_Refactor::RefactorExtractInterfaceCommandMenuItem, hashcode:57879229)
Added handler for: Custom Popup 2699410 '&Implement Interface' (tag: Custom Popup 2699394::RubberduckMenu_Refactor::RefactorImplementInterfaceCommandMenuItem, hashcode:51151019)
Added handler for: Custom Popup 2699410 'Remo&ve Parameters' (tag: Custom Popup 2699394::RubberduckMenu_Refactor::RefactorRemoveParametersCommandMenuItem, hashcode:57705992)
Added handler for: Custom Popup 2699410 'Re&order Parameters' (tag: Custom Popup 2699394::RubberduckMenu_Refactor::RefactorReorderParametersCommandMenuItem, hashcode:49591885)
Added handler for: Custom Popup 2699410 'Move Closer To &Usage' (tag: Custom Popup 2699394::RubberduckMenu_Refactor::RefactorMoveCloserToUsageCommandMenuItem, hashcode:43673788)
Added handler for: Custom Popup 2699410 '&Encapsulate Field' (tag: Custom Popup 2699394::RubberduckMenu_Refactor::RefactorEncapsulateFieldCommandMenuItem, hashcode:57519772)
Added handler for: Custom Popup 2699410 'Introduce &Parameter' (tag: Custom Popup 2699394::RubberduckMenu_Refactor::RefactorIntroduceParameterCommandMenuItem, hashcode:47915903)
Added handler for: Custom Popup 2699410 'Introduce &Field' (tag: Custom Popup 2699394::RubberduckMenu_Refactor::RefactorIntroduceFieldCommandMenuItem, hashcode:28589951)
Added handler for: Custom Popup 2699441 'Current &Procedure' (tag: Custom Popup 2699394::SmartIndenterMenu::IndentCurrentProcedureCommandMenuItem, hashcode:55982972)
Added handler for: Custom Popup 2699441 'Current &Module' (tag: Custom Popup 2699394::SmartIndenterMenu::IndentCurrentModuleCommandMenuItem, hashcode:34084703)
Added handler for: Custom Popup 2699441 'Current Project' (tag: Custom Popup 2699394::SmartIndenterMenu::IndentCurrentProjectCommandMenuItem, hashcode:38326873)
Added handler for: Custom Popup 2699441 '&Add '@NoIndent' (tag: Custom Popup 2699394::SmartIndenterMenu::NoIndentAnnotationCommandMenuItem, hashcode:9397539)
Added handler for: Custom Popup 2699394 'Find &symbol...' (tag: Object Browser::RubberduckMenu::FindSymbolCommandMenuItem, hashcode:17468990)
Added handler for: Custom Popup 2699394 '&Find all references...' (tag: Object Browser::RubberduckMenu::FindAllReferencesCommandMenuItem, hashcode:23003188)
Added handler for: Custom Popup 2699394 'Go to &implementation...' (tag: Object Browser::RubberduckMenu::FindAllImplementationsCommandMenuItem, hashcode:5702100)
Added handler for: Custom Popup 2699456 '&Rename' (tag: MSForms::RubberduckMenu::FormDesignerRefactorRenameCommandMenuItem, hashcode:51318905)
Added handler for: Custom Popup 2699472 '&Rename' (tag: MSForms Control::RubberduckMenu::FormDesignerRefactorRenameCommandMenuItem, hashcode:59216962)
Added handler for: Custom Popup 2699488 '&Rename' (tag: Locals Window::RubberduckMenu::ProjectExplorerRefactorRenameCommandMenuItem, hashcode:63190618)
Added handler for: Custom Popup 2699488 'Find &symbol...' (tag: Locals Window::RubberduckMenu::FindSymbolCommandMenuItem, hashcode:31844657)
Added handler for: Custom Popup 2699488 '&Find all references...' (tag: Locals Window::RubberduckMenu::FindAllReferencesCommandMenuItem, hashcode:18166465)
Added handler for: Custom Popup 2699488 'Go to &implementation...' (tag: Locals Window::RubberduckMenu::FindAllImplementationsCommandMenuItem, hashcode:29280457)
TestEngine created.
2017-06-30 09:11:49.3172;INFO;Rubberduck.UI.Command.VersionCheckCommand;Executing version check.;
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'c:\Users\electassy\Documents\Rubberduck\RetailCoder.VBE\bin\Debug\HtmlAgilityPack.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0xa54 has exited with code 0 (0x0).
The thread 0x8d4 has exited with code 0 (0x0).
The thread 0x9a4 has exited with code 0 (0x0).
The thread 0xf28 has exited with code 0 (0x0).
SubclassingWindow.AssignHandle called for hWnd 394038
The thread 0x510 has exited with code 0 (0x0).
The thread 0xaec has exited with code 0 (0x0).
The thread 0x130c has exited with code 0 (0x0).
The thread 0x5b4 has exited with code 0 (0x0).
SubclassingWindow.AssignHandle called for hWnd 459396
```

**Comment by retailcoder** [comment]
Fixed?

**Comment by shadowofsilicon** [comment]
Nope.  Not fixed or my machine.  Not unless the installer does something I didn’t do manually when I built RD in a new machine last week.

**Comment by MDoerner** [comment]
This issue states that the RD menu is not present in any context menu. I s this really true? Is it not present in the context menu of the project explorer? I can see it there but not in the context menu of the code pane. (Maybe some commandbar or window is wrong.)

**Comment by shadowofsilicon** [comment]
In which context menus should I look for this?

**Comment by MDoerner** [comment]
The Rubberduck menu should be present in the following menus:

- main menu bar
- code pane context menu
- form designer context menu
- form designer control context menu
- project explorer context menu

**Comment by MDoerner** [comment]
I can see a Rubberduck menu in the code pane context menu. However, I just realized that we do not inject the Rubberduck menu in the code pane context menu in break mode. Is this intentional?

**Comment by shadowofsilicon** [comment]
I created a bunch of virtual machines to test a variety of combinations of Windows and Excel.  I orginally thought this was a 32/64bit issue, but now I have no idea.

Results:
![image](https://user-images.githubusercontent.com/28154402/29528082-5394f192-8660-11e7-8b99-2e0f3c354775.png)

The incidence that was originally reported in the issue was observed in a virtual machine instance that I had copied off my company's file server (where Excel was previously installed.)  That VM is Windows 7 64bit and Excel 64bit.  I recently started over with a fresh copy of that VM (think: restored to a snapshot taken after installing Excel and before installing RD) and after installing RD, all context menus appear as expected.

TL;DR, this appears to be a randomly occurring issue.

**Comment by retailcoder** [comment]
Closing with no-repro.
