### ISSUE TITLE
Code Inspection "Object variable 'Cells' is assigned without the 'Set' keyword"

### ISSUE THREAD

**Issue by RaymondWise** [rubberduck-vba/Rubberduck#4037]
I've always had this as a code quality issue and it's always been when I'm writing to a cell e.g.

    Sheet1.Cells(1, 1) = 1

Whereas, of course

    Set Sheet1.Cells(1, 1) = 1

Is not correct. 

What exactly is this inspection looking for that there are so many false positives?

Is this related to https://github.com/rubberduck-vba/Rubberduck/issues/3979 ?

**Comment by MDoerner** [comment]
I think the problem here is with the default member resultion. (There should actually be an inspection result for implicit assignment to the default member.)

The full version of your code is 
```vba
Sheet1.Cells(1,1).Value = 1
```

Is this from last stable release or from a more current version?

There has been a bug in reading the default members from the type libraries of referenced libraries, which has been fixed a few prereleases ago.

**Comment by retailcoder** [comment]
Please confirm which version you're running - thanks!

**Comment by RaymondWise** [comment]
@retailcoder  sorry, 2.2.6672.28001

**Comment by CHR-IS-B** [comment]
I'm also experiencing this with RD version 2.2.6672.28001.

The code below works as expected, writing an array to a worksheet.  The inspection also incorrectly identifies the `Resize` property as the variable being assigned without set (rather than `target`). Let me know if there's anything else that might help with debugging.  Thanks @retailcoder -  RD is awesome!

```
Dim target as Range
Set target = Application.Selection
target.Resize(myArrayCnt, UBound(myArray, 2)) = myArray
```

**Comment by retailcoder** [comment]
@CHR-IS-B thanks! FWIW the assignment target *should* be `Range.[_Default]` (`Resize` returns a `Range`, and it's the default member of that object that is being assigned), not `target`.

**Comment by RaymondWise** [comment]
@MDoerner 

> The full version of your code is
> 
> `Sheet1.Cells(1,1).Value = 1`

The more I consider this, the more it makes sense. Perhaps it's not a bug in the inspection, but instead the inspection needs to say to use the `value` property if you aren't assigning a range to a range.

**Comment by MDoerner** [comment]
This is a resolver bug. The problem is that the resolver did not recognize the default member access. Otherwise, you would have seen a corresponding inspection result.

This should be fixed for a while now. Unfortunately, you are using a version where the displayed version number is not correct. So I cannot say whether the PR that should have fixed this bug came in before or after this version.

**Comment by comintern** [comment]
I can confirm that this is still an issue:

![screenshot from 2018-07-15 10-34-15](https://user-images.githubusercontent.com/8944005/42735506-0f5c2082-881b-11e8-941c-ceb28c9e22b4.png)

**Comment by retailcoder** [comment]
> *What exactly is this inspection looking for that there are so many false positives?*

The inspection means to identify all (most, at least) cases where a `Set` keyword would be required/missing.

What makes this complicated, is the many, *many* curve balls VBA is throwing at us here, which require pretty much flawless identifier resolution, especially of implicit default member calls, which make what has all the looks of an object assignment, actually be a value assignment.

That said, with #4529 it looks like only one known false positive edge case remains.

**Comment by daFreeMan** [comment]
This "real world" (yet minimized) example produces a false positive in build .4244:

```VBA
Public Sub BlankCol(ByVal theRange As Range, ByVal Color As String)
  Dim Theme As Long
  Theme = xlThemeColorLight2
  With theRange.Interior
'@Ignore ObjectVariableNotSet
    .ThemeColor = Theme
  End With
End Sub
```

as is evidenced by the `'@Ignore ObjectVariableNotSet` annotation I had RD install for me.

**HOWEVER** these two MC(n)VEs do NOT generate an inspection result:

```VBA
Private Sub foo()
  Range("a1").Interior.ThemeColor = xlThemeColorLight2
End Sub

Private Sub bar()
  With Range("a1").Interior
    .ThemeColor = xlThemeColorLight2
  End With
End Sub
```

Just for kicks, I changed `Dim Theme As Long` to `Dim Theme As Variant` in my actual code. Made no difference (as would be expected, just confirming).

**Comment by MDoerner** [comment]
To fix the false-positive above we will require a expression type evaluation engine. The problem is that the LHS is Variant and we do not properly evaluate the RHS.

Generally, I would prefer to error on the conservative side and do not generate an inspection result, if we cannot determine properly whether the assignment requires a `Set`.

**Comment by retailcoder** [comment]
That's a bug then... recent tweaks intended the inspection to bail out when LHS is `Variant`

**Comment by retailcoder** [comment]
Need to dig into this - that's supposed to be handled here:

            var simpleName = expression.GetDescendent<VBAParser.SimpleNameExprContext>();
            if (simpleName != null)
            {
                return declarationFinderProvider.DeclarationFinder.MatchName(simpleName.identifier().GetText())
                    .Any(d => AccessibilityCheck.IsAccessible(project, module, reference.ParentScoping, d) && d.IsObject);
            }

`xlThemeColorLight2` wouldn't have `IsObject` be `true`. Presumably the evaluator is returning before it gets to that block.
