### ISSUE TITLE
Consistent crash with build 3357

### ISSUE THREAD

**Issue by Kenshi235** [rubberduck-vba/Rubberduck#4075]
I installed build 3357 today and I am getting a consistent crash in Excel 2016 on Windows 10.
I am new to Rubberduck, and really would like to use this.
To easily reproduce this error:

1) install 3357
2) press ALT + F11 in excel to open VBA editor.
3) If I have a Microsoft Excel Object sheet opened and I go to RubberDuck in VBA --> and click Settings,
All of excel crashes with no warnings.

However, If I open an excel module and close all Microsoft Excel Object sheets, and then go to RubberDuck --> Settings. Excel does not crash.

Attached is my log.txt file. This is such an issue, I must leave this uninstalled for now.

Further notes:
-- this is crashing on a .xlsm file that I have been using for several months with no issue up until this point, and I have splash screen disabled for Rubberduck

-- If I avoid selecting/opening a MS excel object, I can successfully navigate the RubberDuck UI.

-- Anytime I install 3357, I get 2 dialog boxes for to continue installation halfway through, as if I'd be installing one locally and one roaming? I don't understand, but maybe that would be helpful.

-- Issue occurs regardless of whether I have other excel add-ins installed/ticked off.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2091586/RubberduckLog.txt)

I appreciate any help. I think that overall RubberDuck is a great add-in to use.

**Comment by daFreeMan** [comment]
Very weird... I was having the same issue with build .3347 (#4063) in Access, but it was resolved (intentionally or otherwise) in build .3357...

**Comment by retailcoder** [comment]
FWIW .3358 (not merged yet, fixes a ton of autocomplete issues) is still throwing null reference exceptions loading the referenced COM libraries, which seems related to #4063, which is still open.

.3310 would be the most stable recent pre-release build IMO.

**Comment by retailcoder** [comment]
Curious about what's happening during installation. Also I wonder... If you install and then go to `%appdata%\Rubberduck` and delete the .config file, do settings still crash? I'll try to get a repro on Excel 2010 x86,...the relationship with having worksheet modules open is very awkward, I'm not seeing the connection for now.

**Comment by bclothier** [comment]
Following up on this -- apparently the #4063 was closed as fixed, and since it's claimed the issue is related and there has been no other reports, I'll assume this got closed. Please re-open if that is not the case.
